print("welcome to Adirut Shop!")
print("We have a variety of products for you to choose from.")
print("---------------------------------------")
print("1. Banana", 3, 30, "THB : ", 3*30)
print("2. Apple", 5, 50, "THB  : ", 5*50)
print("3. Orange", 2, 20, "THB : ", 2*20)
print("4. Mango", 4, 40, "THB  : ", 4*40)
print("---------------------------------------")
print("Total: ", 3*30 + 5*50 + 2*20 + 4*40, "THB")
print("---------------------------------------")
print("Thank you for shopping with us!")
print("Have a great day!")
print("---------------------------------------")

