print("Hello, World!")
print("Welcome to Python programming.")
print("------------------------------")
print(type("Mixercat"),("Mixercat"))
print(type(5), (5))
print(type(5.0), (5.0))
print(type(True), (True))
print(type(False), (False))
print(type(None), (None))
print(type(1j), (1j))
print(type([1, 2, 3]), ([1, 2, 3]))
print(type((1, 2, 3)), ((1, 2, 3)))
print(type({1, 2, 3}), ({1, 2, 3}))
print(type({'a': 1, 'b': 2}), ({'a': 1, 'b': 2}))
print(type(range(5)), (range(5)))
print(type(len), (len))
print(type(print), (print))
print("------------------------------")