print("Mixercat Shop")
print("--------------------------------------")
print("banana       x 2    = 1.00")
print("apple        x 2    = 1.00")
print("lemon        x 2    = 1.00")
print("cherry       x 2    = 1.00")
print("blueberry    x 2    = 1.00")
print("orange       x 2    = 1.00")
print("strawberry   x 2    = 1.02")
print("mango        x 2    = 1.00")
print("-------------------------------------")
print("Total: 8.02")

print("Thank you for shopping with us!")
print("Have a great day!")
print("Mixercat Shop")
print("--------------------------------------")
print("--------------------------------------")
print("banana       x 2    = 1.00")
print("apple        x 2    = 1.00")
print("lemon        x 2    = 1.00")

x = int(input("Enter Number 1 : "))
y = int(input("Enter Number 2 : "))

print(x>y)